export const description = 'Navegadores aislados para explorar, probar y depurar la web con IA.';

export function page(content) {
  return `<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="${description}"><title>Firetrace · Navegación con IA</title><link rel="icon" type="image/png" href="/logo.png"><style>
  :root{color-scheme:dark;font-family:Inter,ui-sans-serif,system-ui,-apple-system,sans-serif;background:#0d1017;color:#eef0f5}*{box-sizing:border-box}body{margin:0;min-height:100vh;background:radial-gradient(ellipse at 15% 0%,#362016 0,transparent 50%);padding:48px 20px}main{max-width:540px;margin:0 auto}.brand{display:flex;align-items:center;gap:16px;margin-bottom:32px}.brand img{width:64px;height:64px;border-radius:18px}.wordmark{font-size:26px;font-weight:750;letter-spacing:-1px}.eyebrow{color:#ffa85c;font-size:11px;letter-spacing:2px;margin-top:5px;text-transform:uppercase}.card{border:1px solid #303440;background:#151923;border-radius:24px;padding:32px;box-shadow:0 24px 70px #0004}h1{font-size:28px;letter-spacing:-.8px;margin:0 0 20px}p{font-size:14px;line-height:1.65;color:#b9c0cf;overflow-wrap:anywhere}strong{color:#f5f6fa}label{display:block;font-size:14px;font-weight:600;margin-top:26px}input[type=password]{display:block;width:100%;margin-top:10px;background:#0d1017;border:1px solid #4b5365;border-radius:10px;padding:14px;font:inherit;color:#fff}input:focus-visible,button:focus-visible,a:focus-visible{outline:3px solid #ffb66d;outline-offset:3px}button{border:0;border-radius:10px;padding:13px 20px;font:600 14px inherit;cursor:pointer;background:#ff963f;color:#1b1008}button[value=deny]{background:#272e3c;color:#e0e5ef;margin-left:8px}footer{font-size:12px;color:#8f99ab;line-height:1.7;padding:22px 8px}a{color:#ffb66d}code{font-size:12px;overflow-wrap:anywhere}.badge{display:inline-block;padding:6px 10px;background:#252d3a;border-radius:7px;color:#dce2ee;font-size:12px;margin:0 5px 8px 0}@media(max-width:480px){body{padding-top:28px}.card{padding:24px}h1{font-size:25px}}
  </style></head><body><main><header class="brand"><img src="/logo.png" alt="" width="64" height="64"><div><div class="wordmark">Firetrace</div><div class="eyebrow">Explora · Prueba · Depura</div></div></header><section class="card">${content}</section><footer>${description}<br>Sesiones temporales o persistentes. Navegadores visibles o headless.</footer></main></body></html>`;
}

export const home = () => page(`<h1>Tu puente entre la IA y la web.</h1><p>Abre navegadores independientes, interactúa con páginas, toma capturas y analiza solicitudes de red desde tu asistente.</p><p><span class="badge">Sesiones aisladas</span><span class="badge">Headless</span><span class="badge">MCP + OAuth</span></p><p>Para conectar Firetrace, agrega esta dirección como servidor MCP en tu asistente:</p><code>https://firetrace-mcp.braian-n-l.workers.dev/mcp</code><p>El agente Firetrace debe estar abierto en tu equipo para ejecutar acciones.</p>`);
